version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: adminjuegos
      MONGO_INITDB_ROOT_PASSWORD: 123
      MONGO_INITDB_DATABASE: pfJugadores
    ports:
      - "27020:27017"
    volumes:
      - mongodb-data:/data/db

  app:
    build: .
    depends_on:
      - mongodb
    ports:
      - "8085:8085"

volumes:
  mongodb-data:
